<?php

namespace Container5hnc949;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YJTy2ppService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.yJTy2pp' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.yJTy2pp'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'artistRepository' => ['privates', 'App\\Repository\\ArtistRepository', 'getArtistRepositoryService', true],
            'genreRepository' => ['privates', 'App\\Repository\\GenreRepository', 'getGenreRepositoryService', true],
            'repo' => ['privates', 'App\\Repository\\AlbumRepository', 'getAlbumRepositoryService', true],
            'sec' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
        ], [
            'artistRepository' => 'App\\Repository\\ArtistRepository',
            'genreRepository' => 'App\\Repository\\GenreRepository',
            'repo' => 'App\\Repository\\AlbumRepository',
            'sec' => '?',
        ]);
    }
}
