<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5hnc949\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5hnc949/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5hnc949.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5hnc949\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container5hnc949\App_KernelDevDebugContainer([
    'container.build_hash' => '5hnc949',
    'container.build_id' => '391e464a',
    'container.build_time' => 1680428965,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5hnc949');
